### ISSUE TITLE
Boolean parameters are not working

### ISSUE THREAD

**Issue by arjunattam** [microsoft/folio#60]
Passing `-p headful` or `-p screenshotOnFailure` is throwing an error

```
➜  try-runner npx test-runner -p headful
(node:9607) UnhandledPromiseRejectionWarning: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at runTests (/Users/arjun/try-runner/node_modules/@playwright/test-runner/out/cli.js:116:34)
    at Command.<anonymous> (/Users/arjun/try-runner/node_modules/@playwright/test-runner/out/cli.js:63:31)
    at Command.listener [as _actionHandler] (/Users/arjun/try-runner/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/arjun/try-runner/node_modules/commander/index.js:1002:14)
    at Command.parse (/Users/arjun/try-runner/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/Users/arjun/try-runner/node_modules/@playwright/test-runner/out/cli.js:64:13)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/arjun/try-runner/node_modules/@playwright/test-runner/cli.js:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

➜  try-runner npx test-runner -p browserName=webkit

Running 1 test using 1 worker
  1 passed (4s)
```

**Comment by pavelfeldman** [comment]
Fixed
